let photosGallery = [
    {
        all: [
            { img: '/complementos/model1.jpg', descri: 'Description default' },
            { img: '/complementos/model2.jpg', descri: 'Description default' },
            { img: '/complementos/model3.jpg', descri: 'Description default' },
            { img: '/complementos/model4.jpg', descri: 'Description default' },
            { img: '/complementos/model5.jpg', descri: 'Description default' },
            { img: '/complementos/model6.jpg', descri: 'Description default ' },
            { img: '/complementos/model7.jpg', descri: 'Description default ' },
            { img: '/complementos/model8.jpg', descri: 'Description default' },
            { img: '/complementos/model9.jpg', descri: 'Description default ' },
            { img: '/complementos/model10.jpg', descri: 'Description default ' },
            { img: '/complementos/branding1.jpg', descri: 'Description default' },
            { img: '/complementos/branding2.jpg', descri: 'Description default' },
            { img: '/complementos/branding3.jpg', descri: 'Description default' },
            { img: '/complementos/branding4.jpg', descri: 'Description default' },
            { img: '/complementos/branding5.jpg', descri: 'Description default' },
            { img: '/complementos/branding6.jpg', descri: 'Description default' },
            { img: '/complementos/branding7.jpg', descri: 'Description default' },
            { img: '/complementos/branding8.jpg', descri: 'Description default' },
            { img: '/complementos/branding9.jpg', descri: 'Description default' },
            { img: '/complementos/branding10.jpg', descri: 'Description default ' },
            { img: '/complementos/adverts1.jpg', descri: 'Description default' },
            { img: '/complementos/adverts2.jpg', descri: 'Description default' },
            { img: '/complementos/adverts3.jpg', descri: 'Description default' },
            { img: '/complementos/adverts4.jpg', descri: 'Description default' },
            { img: '/complementos/adverts5.jpg', descri: 'Description default' },
            { img: '/complementos/adverts6.jpg', descri: 'Description default' },
            { img: '/complementos/adverts7.jpg', descri: 'Description default' },
            { img: '/complementos/adverts8.jpg', descri: 'Description default' },
            { img: '/complementos/adverts9.jpg', descri: 'Description default' },
            { img: '/complementos/adverts10.jpg', descri: 'Description default' },
            { img: '/complementos/development1.jpg', descri: 'Description default' },
            { img: '/complementos/development2.jpg', descri: 'Description default' },
            { img: '/complementos/development3.jpg', descri: 'Description default' },
            { img: '/complementos/development4.jpg', descri: 'Description default' },
            { img: '/complementos/development5.jpg', descri: 'Description default' },
            { img: '/complementos/development6.jpg', descri: 'Description default' },
            { img: '/complementos/development7.jpg', descri: 'Description default' },
            { img: '/complementos/development8.jpg', descri: 'Description default' },
            { img: '/complementos/development9.jpg', descri: 'Description default' },
            { img: '/complementos/development10.jpg', descri: 'Description default' },
        ],
    },
    {
        models: [
            { img: '/complementos/model1.jpg', descri: 'Description default' },
            { img: '/complementos/model2.jpg', descri: 'Description default' },
            { img: '/complementos/model3.jpg', descri: 'Description default' },
            { img: '/complementos/model4.jpg', descri: 'Description default' },
            { img: '/complementos/model5.jpg', descri: 'Description default' },
            { img: '/complementos/model6.jpg', descri: 'Description default' },
            { img: '/complementos/model7.jpg', descri: 'Description default ' },
            { img: '/complementos/model8.jpg', descri: 'Description default' },
            { img: '/complementos/model9.jpg', descri: 'Description default ' },
            { img: '/complementos/model10.jpg', descri: 'Description default ' },
        ],
    },
    {
        branding: [
            { img: '/complementos/branding1.jpg', descri: 'Description default' },
            { img: '/complementos/branding2.jpg', descri: 'Description default' },
            { img: '/complementos/branding3.jpg', descri: 'Description default' },
            { img: '/complementos/branding4.jpg', descri: 'Description default' },
            { img: '/complementos/branding5.jpg', descri: 'Description default' },
            { img: '/complementos/branding6.jpg', descri: 'Description default' },
            { img: '/complementos/branding7.jpg', descri: 'Description default' },
            { img: '/complementos/branding8.jpg', descri: 'Description default' },
            { img: '/complementos/branding9.jpg', descri: 'Description default' },
            { img: '/complementos/branding10.jpg', descri: 'Description default' },
        ],
    },
    {
        adverts: [
            { img: '/complementos/adverts1.jpg', descri: 'Description default' },
            { img: '/complementos/adverts2.jpg', descri: 'Description default' },
            { img: '/complementos/adverts3.jpg', descri: 'Description default' },
            { img: '/complementos/adverts4.jpg', descri: 'Description default' },
            { img: '/complementos/adverts5.jpg', descri: 'Description default' },
            { img: '/complementos/adverts6.jpg', descri: 'Description default' },
            { img: '/complementos/adverts7.jpg', descri: 'Description default' },
            { img: '/complementos/adverts8.jpg', descri: 'Description default' },
            { img: '/complementos/adverts9.jpg', descri: 'Description default' },
            { img: '/complementos/adverts10.jpg', descri: 'Description default' },
        ],
    },
    {
        development: [
            { img: '/complementos/development1.jpg', descri: 'Description default' },
            { img: '/complementos/development2.jpg', descri: 'Description default' },
            { img: '/complementos/development3.jpg', descri: 'Description default' },
            { img: '/complementos/development4.jpg', descri: 'Description default' },
            { img: '/complementos/development5.jpg', descri: 'Description default' },
            { img: '/complementos/development6.jpg', descri: 'Description default' },
            { img: '/complementos/development7.jpg', descri: 'Description default' },
            { img: '/complementos/development8.jpg', descri: 'Description default' },
            { img: '/complementos/development9.jpg', descri: 'Description default' },
            { img: '/complementos/development10.jpg', descri: 'Description default' },
        ],
    },
];
